# -*- generated by 1.0.12 -*-
import da
PatternExpr_197 = da.pat.TuplePattern([da.pat.ConstantPattern('msg02'), da.pat.FreePattern('m')])
PatternExpr_204 = da.pat.BoundPattern('_BoundPattern205_')
PatternExpr_263 = da.pat.TuplePattern([da.pat.ConstantPattern('msg01'), da.pat.FreePattern('m')])
PatternExpr_270 = da.pat.FreePattern('A')
_config_object = {}
from sa.secalgoB import *

class RoleA(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._RoleAReceivedEvent_0 = []
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_RoleAReceivedEvent_0', PatternExpr_197, sources=[PatternExpr_204], destinations=None, timestamps=None, record_history=True, handlers=[])])

    def setup(self, skA, B, pkB, **rest_344):
        super().setup(skA=skA, B=B, pkB=pkB, **rest_344)
        self._state.skA = skA
        self._state.B = B
        self._state.pkB = pkB
        at_fork()

    def run(self):
        k = keygen('shared')
        self.send(('msg01', encrypt(sign(k, key=self._state.skA), key=self._state.pkB)), to=self._state.B)
        super()._label('_st_label_194', block=False)
        m = None

        def ExistentialOpExpr_195():
            nonlocal m
            for (_, (_, _, _BoundPattern212_), (_ConstantPattern214_, m)) in self._RoleAReceivedEvent_0:
                if (_BoundPattern212_ == self._state.B):
                    if (_ConstantPattern214_ == 'msg02'):
                        if True:
                            return True
            return False
        _st_label_194 = 0
        while (_st_label_194 == 0):
            _st_label_194 += 1
            if ExistentialOpExpr_195():
                _st_label_194 += 1
            else:
                super()._label('_st_label_194', block=True)
                _st_label_194 -= 1
        s = decrypt(m, key=k)
        self.output('DECRYPTED MESSAGE:', s)

class RoleB(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_RoleBReceivedEvent_0', PatternExpr_263, sources=[PatternExpr_270], destinations=None, timestamps=None, record_history=None, handlers=[self._RoleB_handler_262])])

    def setup(self, skB, pkA, **rest_344):
        super().setup(skB=skB, pkA=pkA, **rest_344)
        self._state.skB = skB
        self._state.pkA = pkA
        self._state.terminate = False
        at_fork()
        self._state.s = 'secret'

    def run(self):
        super()._label('_st_label_258', block=False)
        _st_label_258 = 0
        while (_st_label_258 == 0):
            _st_label_258 += 1
            if self._state.terminate:
                _st_label_258 += 1
            else:
                super()._label('_st_label_258', block=True)
                _st_label_258 -= 1

    def _RoleB_handler_262(self, m, A):
        k = verify(decrypt(m, key=self._state.skB), key=self._state.pkA)
        self.send(('msg02', encrypt(self._state.s, key=k)), to=A)
        self._state.terminate = True
    _RoleB_handler_262._labels = None
    _RoleB_handler_262._notlabels = None

class Node_(da.NodeProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])

    def run(self):
        (skA, pkA) = keygen('public')
        (skB, pkB) = keygen('public')
        B = self.new(RoleB, (skB, pkA))
        A = self.new(RoleA, (skA, B, pkB))
        self._start(A)
        self._start(B)
