# -*- generated by 1.0.12 -*-
import da
PatternExpr_223 = da.pat.TuplePattern([da.pat.ConstantPattern('msg2'), da.pat.BoundPattern('_BoundPattern226_'), da.pat.BoundPattern('_BoundPattern227_'), da.pat.BoundPattern('_BoundPattern228_'), da.pat.FreePattern('dh_Y'), da.pat.FreePattern('m')])
PatternExpr_235 = da.pat.BoundPattern('_BoundPattern236_')
PatternExpr_339 = da.pat.TuplePattern([da.pat.ConstantPattern('msg1'), da.pat.FreePattern('i'), da.pat.FreePattern('A'), da.pat.FreePattern('s'), da.pat.FreePattern('dh_X')])
PatternExpr_352 = da.pat.BoundPattern('_BoundPattern353_')
PatternExpr_402 = da.pat.TuplePattern([da.pat.ConstantPattern('msg3'), da.pat.BoundPattern('_BoundPattern405_'), da.pat.BoundPattern('_BoundPattern406_'), da.pat.BoundPattern('_BoundPattern407_'), da.pat.FreePattern('m')])
PatternExpr_412 = da.pat.BoundPattern('_BoundPattern413_')
_config_object = {}
from sa.secalgoB import *
configure(verify_returns='bool')

class RoleA(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._RoleAReceivedEvent_0 = []
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_RoleAReceivedEvent_0', PatternExpr_223, sources=[PatternExpr_235], destinations=None, timestamps=None, record_history=True, handlers=[])])

    def setup(self, skSigA, pkSigA, B, pkSigB, p, g, **rest_517):
        super().setup(skSigA=skSigA, pkSigA=pkSigA, B=B, pkSigB=pkSigB, p=p, g=g, **rest_517)
        self._state.skSigA = skSigA
        self._state.pkSigA = pkSigA
        self._state.B = B
        self._state.pkSigB = pkSigB
        self._state.p = p
        self._state.g = g
        at_fork()
        self._state.i = 1

    @dec_proto_run_timer
    def run(self):
        s = nonce(128)
        (dh_x, dh_X, _, _) = keygen('dh', dh_p=self._state.p, dh_g=self._state.g)
        self.send(('msg1', self._state.i, self._id, s, dh_X), to=self._state.B)
        super()._label('_st_label_220', block=False)
        m = dh_Y = None

        def ExistentialOpExpr_221():
            nonlocal m, dh_Y
            for (_, (_, _, _BoundPattern243_), (_ConstantPattern245_, _BoundPattern247_, _BoundPattern248_, _BoundPattern249_, dh_Y, m)) in self._RoleAReceivedEvent_0:
                if (_BoundPattern243_ == self._state.B):
                    if (_ConstantPattern245_ == 'msg2'):
                        if (_BoundPattern247_ == self._state.i):
                            if (_BoundPattern248_ == self._state.B):
                                if (_BoundPattern249_ == s):
                                    if True:
                                        return True
            return False
        _st_label_220 = 0
        while (_st_label_220 == 0):
            _st_label_220 += 1
            if ExistentialOpExpr_221():
                _st_label_220 += 1
            else:
                super()._label('_st_label_220', block=True)
                _st_label_220 -= 1
        if (not (verify(((self._state.B, s, dh_Y, dh_X, self._id), m), key=self._state.pkSigB) == None)):
            self.send(('msg3', self._state.i, self._id, s, sign((self._id, s, dh_X, dh_Y, self._state.B), key=self._state.skSigA)), to=self._state.B)
            kAB = pow(dh_Y, dh_x, self._state.p)
            dh_x = None
            self.output('A - Authenticated Exchange of Key Material Complete')
        self._state.i += 1

class RoleB(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._RoleBReceivedEvent_1 = []
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_RoleBReceivedEvent_0', PatternExpr_339, sources=[PatternExpr_352], destinations=None, timestamps=None, record_history=None, handlers=[self._RoleB_handler_338]), da.pat.EventPattern(da.pat.ReceivedEvent, '_RoleBReceivedEvent_1', PatternExpr_402, sources=[PatternExpr_412], destinations=None, timestamps=None, record_history=True, handlers=[])])

    def setup(self, skSigB, pkSigB, pkSigA, p, g, **rest_517):
        super().setup(skSigB=skSigB, pkSigB=pkSigB, pkSigA=pkSigA, p=p, g=g, **rest_517)
        self._state.skSigB = skSigB
        self._state.pkSigB = pkSigB
        self._state.pkSigA = pkSigA
        self._state.p = p
        self._state.g = g
        at_fork()
        self._state.terminate = False

    @dec_proto_run_timer
    def run(self):
        self._state.terminate = False
        super()._label('_st_label_334', block=False)
        _st_label_334 = 0
        while (_st_label_334 == 0):
            _st_label_334 += 1
            if self._state.terminate:
                _st_label_334 += 1
            else:
                super()._label('_st_label_334', block=True)
                _st_label_334 -= 1

    def _RoleB_handler_338(self, i, A, s, dh_X):
        (dh_y, dh_Y, _, _) = keygen('dh', dh_p=self._state.p, dh_g=self._state.g)
        self.send(('msg2', i, self._id, s, dh_Y, sign((self._id, s, dh_Y, dh_X, A), key=self._state.skSigB)), to=A)
        kAB = pow(dh_X, dh_y, self._state.p)
        dh_y = None
        super()._label('_st_label_399', block=False)
        m = None

        def ExistentialOpExpr_400():
            nonlocal m
            for (_, (_, _, _BoundPattern420_), (_ConstantPattern422_, _BoundPattern424_, _BoundPattern425_, _BoundPattern426_, m)) in self._RoleBReceivedEvent_1:
                if (_BoundPattern420_ == A):
                    if (_ConstantPattern422_ == 'msg3'):
                        if (_BoundPattern424_ == i):
                            if (_BoundPattern425_ == A):
                                if (_BoundPattern426_ == s):
                                    if True:
                                        return True
            return False
        _st_label_399 = 0
        while (_st_label_399 == 0):
            _st_label_399 += 1
            if ExistentialOpExpr_400():
                _st_label_399 += 1
            else:
                super()._label('_st_label_399', block=True)
                _st_label_399 -= 1
        if (not (verify(((A, s, dh_X, dh_Y, self._id), m), key=self._state.pkSigA) == None)):
            self.output('B - Authenticated Exchange of Key Material Complete')
        self._state.terminate = True
    _RoleB_handler_338._labels = None
    _RoleB_handler_338._notlabels = None

class Node_(da.NodeProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])

    def run(self):
        (skSigA, pkSigA) = keygen('public')
        (skSigB, pkSigB) = keygen('public')
        (_, _, dh_g, dh_p) = keygen('dh', dh_group=17)
        B = self.new(RoleB, (skSigB, pkSigB, pkSigA, dh_p, dh_g))
        A = self.new(RoleA, (skSigA, pkSigA, B, pkSigB, dh_p, dh_g))
        self._start(B)
        self._start(A)
